# Generated by Django 2.2.4 on 2020-07-02 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_first', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('mission_first', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('vision_first', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('plan_first', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('care_first', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('mission', models.CharField(max_length=120)),
                ('vision', models.CharField(max_length=120)),
                ('plan', models.CharField(max_length=120)),
                ('care', models.CharField(max_length=120)),
                ('about_content_description', models.TextField(blank=True, null=True)),
                ('mission_content_description', models.TextField(blank=True, null=True)),
                ('vision_content_description', models.TextField(blank=True, null=True)),
                ('plan_content_description', models.TextField(blank=True, null=True)),
                ('care_content_description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
