# Generated by Django 2.2.4 on 2020-07-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_testimonial', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('name', models.CharField(max_length=120)),
                ('proffesion', models.CharField(max_length=120)),
                ('testimony', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='about',
            old_name='care_first',
            new_name='care_image',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='mission_first',
            new_name='mission_image',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='plan_first',
            new_name='plan_image',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='vision_first',
            new_name='vision_image',
        ),
    ]
