# Generated by Django 2.2.4 on 2020-07-02 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20200702_0912'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
