# Generated by Django 2.2.4 on 2020-07-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text', models.TextField()),
                ('secondary_text', models.TextField()),
                ('button_link', models.CharField(max_length=120)),
            ],
        ),
    ]
